INPUT_FILE = "add_infrastructure_id/FICHE_POINT_DEAU15_04_2024_20260604.xlsx"
OUTPUT_FILE = "add_infrastructure_id/FICHE_POINT_DEAU15_04_2024_with_infrastructure_id_20260604.xlsx"
KOBO_BASE_URL = "https://kf.kobotoolbox.org"
API_TOKEN = "77b1fc042633c4fbc87ce357ecebf183b877d5f8"
SUBMISSION_URL = f"{KOBO_BASE_URL}/submission"
FORM_ID_STRING = "aBVC89L2geR3UwAkLyZm8K"
ASSET_SCHEMA_URL = f"{KOBO_BASE_URL}/api/v2/assets/{FORM_ID_STRING}.json"
FORM_VERSION = "2404150901"
HEADERS = {"Authorization": f"Token {API_TOKEN}"}

infra_type_mapping = {
    "FICHE_MARCHES_A_BETAIL": 1,
    "FICHE_PARC_DE_VACCINATION": 2,
    "FICHE_POINT_D_EAU": 3,
    "FICHE_UNITE_VETERINAIRE": 4,
}

infra_acronym_mapping = {
    "FICHE_MARCHES_A_BETAIL": "MB",
    "FICHE_PARC_DE_VACCINATION": "PV",
    "FICHE_POINT_D_EAU": "PE",
    "FICHE_UNITE_VETERINAIRE": "UV",
}

mapping_dict_water_points = {
    "starttime": "starttime",
    "endtime": "endtime",
    "deviceid": "deviceid",
    "devicephonenum": "devicephonenum",
    "DATE": "DATE",
    "IDPE1": "IDUV1",
    "IDPE2": "IDUV2",
    "IDPE2a": "IDUV2a",
    "IDPE3": "IDUV3",
    "IDPE4": "",
    "IDPE5": "",
    "IDPE6": "",
    "IDPE7": "IDUV7",
    "IDPE8": "IDUV8",
    "IDPE8a": "",
    "IDPE9": "IDUV9",
    "LPE1": "LUV1",
    "LPE2": "LUV2",
    "LPE3": "LUV3",
    "LPE4": "LUV4",
    "LPE5": "LUV5",
    "TYPE": "TYPE",
    "CDR": "CDR",
    "HCDR": "HCDR",
    "TYPE_ACRONYM": "TYPE_ACRONYM",
    "LPE6": "",
    "LPE7": "LUV6",
    "_LPE7_latitude": "_LUV6_latitude",
    "_LPE7_longitude": "_LUV6_longitude",
    "_LPE7_altitude": "_LUV6_altitude",
    "_LPE7_precision": "_LUV6_precision",
    "INFRASTRUCTURE_ID": "INFRASTRUCTURE_ID",
    "geometry": "geometry",
    "latitude": "latitude",
    "longitude": "longitude",
    "LPE8": "LUV7",
    "LPE8a": "LUV7a",
    "LPE8a_URL": "LUV7a_URL",
    "LPE8b": "LUV7b",
    "LPE8b_URL": "LUV7b_URL",
    "LPE8c": "LUV7c",
    "LPE8c_URL": "LUV7c_URL",
    "LPE8d": "LUV7d",
    "LPE8d_URL": "LUV7d_URL",
    "LPE9": "",
    "IGPE1": "",
    "IGPE1a": "",
    "IGPE2": "",
    "IGPE3": "",
    "IGPE4": "",
    "IGPE5": "",
    "IGPE6": "",
    "IGPE7": "",
    "IGPE10": "",
    "IGPE11": "",
    "IGPE11A1": "",
    "IGPE11A2": "",
    "IGPE11A3": "",
    "IGPE11A3/1": "",
    "IGPE11A3/2": "",
    "IGPE11A3/3": "",
    "IGPE11A3/4": "",
    "IGPE11A3/5": "",
    "IGPE11A3/6": "",
    "IGPE11A3/7": "",
    "IGPE11A4": "",
    "IGPE11A5": "",
    "IGPE11A6": "",
    "IGPE11A7": "",
    "IGPE11A8": "",
    "IGPE11A9": "",
    "STPE1": "STMB1",
    "STPE2": "",
    # STMB2
    "STPE3": "STMB3",
    "STPE4": "STMB4",
    "STPE5": "STMB5",
    "STPE6": "",
    "STPE7": "",
    "STPE8": "",
    "STPE9": "",
    "STPE10": "",
    "STPE11": "STMB11",
    "STPE12": "STMB12",
    "STPE13": "STMB13",
    "STPE14": "STMB14",
    "STPE15": "STMB15",
    "STPE16": "",
    "STPE17": "",
    "STPE18": "",
    "CFPE1": "",
    "CFPE1a": "",
    "CFPE2": "",
    "CFPE3": "",
    "CFPE4": "",
    "CFPE5": "",
    "CFPE6": "",
    "CFPE7": "",
    "VALPE1": "",
    "VALPE2": "",
    "VALPE3": "",
    "VALPE4": "",
    "VALPE5": "",
    "VALPE6": "",
    "SAUPE1": "",
    "SAUPE2": "",
    "SAUPE3": "",
    "SAUPE4": "",
    "SAUPE5": "",
    "SAUPE6": "",
    "SAUPE6/1": "",
    "SAUPE6/2": "",
    "SAUPE6a": "",
    "SAUPE7": "",
    "SAUPE7/1": "",
    "SAUPE7/2": "",
    "SAUPE7/3": "",
    "SAUPE8": "",
    "SAUPE9": "",
    "SAUPE10": "",
    "SAUPE11": "",
    "SAUPE12": "",
    "SAUPE13": "",
    "SAUPE14": "",
    "SAUPE15": "",
    "_id": "_id",
    "_uuid": "_uuid",
    "_submission_time": "_submission_time",
    "_validation_status": "_validation_status",
    "_notes": "_notes",
    "_status": "_status",
    "_submitted_by": "_submitted_by",
    "__version__": "__version__",
    "_tags": "_tags",
    "meta/rootUuid": "meta/rootUuid",
    "_index": "_index",
}
