INPUT_FILES = [
    "add_infrastructure_id/inputs/FICHE_POINT_DEAU15_04_2024.xlsx",
    "add_infrastructure_id/inputs/FICHE_PARC_DE_VACCINATION15_04_2024.xlsx",
    "add_infrastructure_id/inputs/FICHE_MARCHES_A_BETAIL.xlsx",
    "add_infrastructure_id/inputs/FICHE_UNITE_VETERINAIRE.xlsx",
    "add_infrastructure_id/inputs/FICHE AIRE D'ABATTAGE, ETAL, MAGASINS, LATRINES_MALI.xlsx",
]
INPUT_FILES_OTHER = [
    "add_infrastructure_id/inputs/FICHE AIRE D'ABATTAGE, ETAL, MAGASINS, LATRINES_MALI.xlsx",
]
OUTPUT_PATH = "add_infrastructure_id/outputs/"
KOBO_BASE_URL = "https://kf.kobotoolbox.org"
API_TOKEN = "77b1fc042633c4fbc87ce357ecebf183b877d5f8"
SUBMISSION_URL = f"{KOBO_BASE_URL}/submission"
FORM_ID_STRING = "aRZ43wRerX8pCdo4XrKw4n"
ASSET_SCHEMA_URL = f"{KOBO_BASE_URL}/api/v2/assets/{FORM_ID_STRING}.json"
FORM_VERSION = "2404150901"
HEADERS = {"Authorization": f"Token {API_TOKEN}"}

geoloc_cols_mapping = {
    "FICHE_POINT_DEAU15_04_2024": "LPE7",
    "FICHE_PARC_DE_VACCINATION15_04_2024": "LVAC6",
    "FICHE_MARCHES_A_BETAIL": "LMB6",
    "FICHE_UNITE_VETERINAIRE": "LUV6",
    "FICHE AIRE D'ABATTAGE, ETAL, MAGASINS, LATRINES_MALI": "_16_Coordonn_es_g_og_de_l_aire_d_abattage",
}

# province_cols_mapping = {
#     "FICHE_POINT_DEAU15_04_2024": "LPE3",
#     "FICHE_PARC_DE_VACCINATION15_04_2024": "LVAC3",
#     "FICHE_MARCHES_A_BETAIL": "LMB3",
#     "FICHE_UNITE_VETERINAIRE": "LUV3",
# }

infra_acronym_mapping = {
    "FICHE_MARCHES_A_BETAIL": "MB",
    "FICHE_PARC_DE_VACCINATION15_04_2024": "PV",
    "FICHE_POINT_DEAU15_04_2024": "PE",
    "FICHE_UNITE_VETERINAIRE": "UV",
}

infra_type_mapping = {
    "FICHE_MARCHES_A_BETAIL": 1,
    "FICHE_PARC_DE_VACCINATION15_04_2024": 2,
    "FICHE_POINT_DEAU15_04_2024": 3,
    "FICHE_UNITE_VETERINAIRE": 4,
}

infra_type_col_mali = "_19_Types_d_infrastructures"

collector_function_col_mali = "_3_Fonction_du_collecteur"
collector_contact_col_mali = "_4_Contact_t_l_phonique_du_collecteur"
controller_contact_col_mali = "_7_Contact_t_l_phonique_du_contr_leur"
investigated_contact_col_mali = "_10_Contact_t_l_phonique_du_contr_leur"
country_col_mali = "_11_Pays"
work_type_col_mali = "_29_Quelle_est_la_na_des_travaux_r_alis_s"
work_duration_col_mali = "_32_Quelle_est_la_du_s_travaux_en_mois_"
implementation_level_col_mali = "_33_Pr_cisez_le_niveau_de_mise"
reception_date_col_mali = "_41_Si_r_ception_d_f_er_la_date_voir_PV"
work_completion_rate_col_mali = "_42_Pr_cisez_le_taux_la_date_de_l_enqu_te"

collector_function_code_mapping_mali = {
    "assistant_en_s_e": 1,
    "point_focal": 2,
    "agent_collecte": 3,
    "autre___pr_ciser": 4,
}

infra_type_acronym_mapping_mali = {
    "magasin_d_aliment_betail": "MAB",
    "aire_d_abattage": "AA",
    "latrine_et_habri_vaccin": "LHV",
    "etal_de_boucherie": "EB",
    "cloture_uapia": "CU",
    "magasin_de_stock_de_consomable_de_laboratoire": "MSCL",
    None: "AUTRE",
}

infra_type_mapping_mali = {
    "magasin_d_aliment_betail": 4,
    "aire_d_abattage": 1,
    "latrine_et_habri_vaccin": 13,
    "etal_de_boucherie": 3,
    "cloture_uapia": 13,
    "magasin_de_stock_de_consomable_de_labora": 13,
    None: 13,
}

work_type_code_mapping_mali = {
    "construction": 1,
    "r_habilitation": 2,
}

work_duration_code_mapping_mali = {
    "45jour": "2",
    "Pas encore commence": "0",
}

implementation_level_code_mapping_mali = {
    "pas_encore_d_marr": 1,
    "travaux_en_cours__progression_normale": 2,
    "travaux_en_cours__retard": 3,
    "travaux_en_arr_t": 4,
    "r_ception_provisoire_avec_reserve": 5,
    "r_ception_provisoire_sans_reserve": 6,
    "r_ception_d_finitive": 7,
}

work_completion_rate_code_mapping = {
    "pas_commenc___0": None,
    "moins_de_25": 1,
    "entre_25_et_50": 2,
    "entre_50_et_75": 3,
    "plus_de_75": 4,
    "achev___100": 7,
}

all_forms_cols_mapping = {
    # common fields to keep
    "starttime": "starttime",
    "endtime": "endtime",
    "deviceid": "deviceid",
    "devicephonenum": "devicephonenum",
    "praps2": "praps2",
    "IDENTIFICATION_DU_CO_TEUR_ET_DE_L_ENQUETE": "IDENTIFICATION_DU_CO_TEUR_ET_DE_L_ENQUETE",
    "DATE": "DATE",
    "_id": "_id",
    "_uuid": "_uuid",
    "_submission_time": "_submission_time",
    "_validation_status": "_validation_status",
    "_notes": "_notes",
    "_status": "_status",
    "_submitted_by": "_submitted_by",
    "__version__": "__version__",
    "_tags": "_tags",
    "meta/rootUuid": "meta/rootUuid",
    "_index": "_index",
    # common fields to ignore
    "SAUVEGARDES_ENVIRONN_BASEES_SUR_LE_GENRE": "",
    # new fields added
    "TYPE": "TYPE",
    "CDR": "CDR",
    # IGPE0 --> 10) Choisir le type d'unité vétérinaire concerné
    # IGPE0a --> 10a) Si autre (Précisez )
    # IGPE1 --> 11) Choisir le type de point d’eau pastoral concerné
    # IGPE1a --> 11a) Si autre (Précisez )
    # IGPE2 --> 12) Quels sont les moyens d’exhaure du point d'eau?
    # IGPE2/1
    # IGPE2/2
    # IGPE2/3
    # IGPE2/4
    # IGPE2/5
    # IGPE2/6
    # IGPE2a
    "HCDR": "HCDR",
    "TYPE_ACRONYM": "TYPE_ACRONYM",
    # BASE_ID
    # MATCHING_ID
    "INFRASTRUCTURE_ID": "INFRASTRUCTURE_ID",
    # IDT
    # IDT2
    "geometry": "geometry",
    "latitude": "latitude",
    "longitude": "longitude",
    # fields only in fiche simplifié
    # STMB2 --> 14) Quel est le nom de l'entreprise en charge des travaux?
    # STMB0 --> 15) Est-ce la première collecte de données sur ce site ?
    # IDT --> 16) Saisie de l’identifiant de l’infrastructure
    # STMB01 --> 17) Nom de l'organisme en charge du contrôle des travaux
    # STMB02 --> 18) Nom et prénom du représentant légal ou du responsable du bureau de contrôle
    # STMB03 --> 19) Contact du représentant légal du bureau de contrôle
    # CONFSITE --> Observations sur le site
    # CONFSITE1 --> 25) Quelle est la qualité globale des travaux réalisés?
    # DATTROL --> 26) Quelle est la date de la dernière visite du Bureau de contrôle ?
    # CONFSITE2 --> 27) Quels sont vos commentaires généraux sur l'exécution des travaux sur le chantier?
    # STMB16 --> 28) Tracker le couloir
    # STMB17 --> distance(${STMB16})
    # STMB18 --> ${STMB17}div1000
    # note4 --> 29) La distance trackée est ${STMB18} Kilomètre (s)
    # fields in FICHE_POINT_DEAU
    "IDPE1": "IDUV1",
    "IDPE2": "IDUV2",
    "IDPE2a": "IDUV2A",
    "IDPE3": "IDUV3",
    "IDPE4": "",
    "IDPE5": "",
    "IDPE6": "",
    "IDPE7": "IDUV7",
    "IDPE8": "IDUV8",
    "IDPE8a": "",
    "IDPE9": "IDUV9",
    "LOCALISATION_DU_POINT_D_EAU_PASTORAL": "LOCALISATION_DE_L_INFRASTRUCTURE",
    "LPE1": "LUV1",
    "LPE2": "LUV2",
    "LPE3": "LUV3",
    "LPE4": "LUV4",
    "LPE5": "LUV5",
    "LPE6": "",
    "LPE7": "LUV6",
    "_LPE7_latitude": "_LUV6_latitude",
    "_LPE7_longitude": "_LUV6_longitude",
    "_LPE7_altitude": "_LUV6_altitude",
    "_LPE7_precision": "_LUV6_precision",
    "LPE8": "LUV7",
    "LPE8a": "LUV7a",
    "LPE8a_URL": "LUV7a_URL",
    "LPE8b": "LUV7b",
    "LPE8b_URL": "LUV7b_URL",
    "LPE8c": "LUV7c",
    "LPE8c_URL": "LUV7c_URL",
    "LPE8d": "LUV7d",
    "LPE8d_URL": "LUV7d_URL",
    "LPE9": "",
    "INFORMATION_GENERALE_POINT_D_EAU_PASTORAL": "",
    "IGPE1": "IGPE1",
    "IGPE1a": "IGPE1a",
    "IGPE2": "",
    "IGPE3": "",
    "IGPE4": "",
    "IGPE5": "",
    "IGPE6": "",
    "IGPE7": "",
    "IGPE10": "",
    "IGPE11": "",
    "IGPE11A1": "",
    "IGPE11A2": "",
    "IGPE11A3": "",
    "IGPE11A3/1": "",
    "IGPE11A3/2": "",
    "IGPE11A3/3": "",
    "IGPE11A3/4": "",
    "IGPE11A3/5": "",
    "IGPE11A3/6": "",
    "IGPE11A3/7": "",
    "IGPE11A4": "",
    "IGPE11A5": "",
    "IGPE11A6": "",
    "IGPE11A7": "",
    "IGPE11A8": "",
    "IGPE11A9": "",
    "SUIVI_DES_TRAVAUX_DE_POINT_D_EAU_PASTORAL": "SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE",
    "STPE1": "STMB1",
    "STPE2": "",
    "STPE3": "STMB3",
    "STPE4": "STMB4",
    "STPE5": "STMB5",
    "STPE6": "",
    "STPE7": "",
    "STPE8": "",
    "STPE9": "",
    "STPE10": "",
    "STPE11": "STMB11",
    "STPE12": "STMB12",
    "STPE13": "STMB13",
    "STPE14": "STMB14",
    "STPE15": "STMB15",
    "STPE16": "",
    "STPE17": "",
    "STPE18": "",
    "CRITERE_DE_FONCTIONN_POINT_D_EAU_PASTORAL": "",
    "CFPE1": "IGPE2",
    "CFPE1a": "IGPE2a",
    "CFPE2": "",
    "CFPE3": "",
    "CFPE4": "",
    "CFPE5": "",
    "CFPE6": "",
    "CFPE7": "",
    "VALORISATION_DU_POINT_D_EAU_PASTORAL": "",
    "VALPE1": "",
    "VALPE2": "",
    "VALPE3": "",
    "VALPE4": "",
    "VALPE5": "",
    "VALPE6": "",
    "SAUPE1": "",
    "SAUPE2": "",
    "SAUPE3": "",
    "SAUPE4": "",
    "SAUPE5": "",
    "SAUPE6": "",
    "SAUPE6/1": "",
    "SAUPE6/2": "",
    "SAUPE6a": "",
    "SAUPE7": "",
    "SAUPE7/1": "",
    "SAUPE7/2": "",
    "SAUPE7/3": "",
    "SAUPE8": "",
    "SAUPE9": "",
    "SAUPE10": "",
    "SAUPE11": "",
    "SAUPE12": "",
    "SAUPE13": "",
    "SAUPE14": "",
    "SAUPE15": "",
    # fields in FICHE_PARC_DE_VACCINATION15_04_2024
    "FICHE_DE_VACCINATION": "",
    "IDVAC1": "IDUV1",
    "IDVAC2": "IDUV2",
    "IDVAC2a": "IDUV2A",
    "IDVAC3": "IDUV3",
    "IDVAC4": "",
    "IDVAC5": "",
    "IDVAC6": "",
    "IDVAC7": "IDUV7",
    "IDVAC8": "IDUV8",
    "IDVAC9": "IDUV9",
    "LOCALISATION_DU_PARC_DE_VACCINATION": "LOCALISATION_DE_L_INFRASTRUCTURE",
    "LVAC1": "LUV1",
    "LVAC2": "LUV2",
    "LVAC3": "LUV3",
    "LVAC4": "LUV4",
    "LVAC5": "LUV5",
    "LVAC6": "LUV6",
    "_LVAC6_latitude": "_LUV6_latitude",
    "_LVAC6_longitude": "_LUV6_longitude",
    "_LVAC6_altitude": "_LUV6_altitude",
    "_LVAC6_precision": "_LUV6_precision",
    "Prendre_quelques_ph_s_angles_ou_facettes": "LUV7",
    "LVAC8a": "LUV7a",
    "LVAC8a_URL": "LUV7a_URL",
    "LVAC8b": "LUV7b",
    "LVAC8b_URL": "LUV7b_URL",
    "LVAC8c": "LUV7c",
    "LVAC8c_URL": "LUV7c_URL",
    "LVAC8d": "LUV7d",
    "LVAC8d_URL": "LUV7d_URL",
    "LVAC9": "",
    "INFORMATION_GENERALE_PARC_DE_VACCINATION": "",
    "IGVAC1": "",
    "IGVAC2": "",
    "IGVAC3": "",
    "IGVAC4": "",
    "IGVAC5": "",
    "IGVAC6": "",
    "IGVAC7": "",
    "IGVAC8": "",
    "IGVAC9": "",
    "IGVAC10": "",
    "IGVAC11": "",
    "IGVAC12": "",
    "IGVAC12I": "",
    "IGVAC12C": "",
    "IGVAC12A": "",
    "IGVAC12A/1": "",
    "IGVAC12A/2": "",
    "IGVAC12A/3": "",
    "IGVAC12A/4": "",
    "IGVAC12A/5": "",
    "IGVAC12A/6": "",
    "IGVAC12A/7": "",
    "IGVAC12A1": "",
    "IGVAC12A2": "",
    "IGVAC12A3": "",
    "IGVAC12A4": "",
    "IGVAC12A5": "",
    "IGVAC12A6": "",
    "SUIVI_DES_TRAVAUX_DE_U_PARC_A_VACCINATION": "SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE",
    "STVAC1": "STMB1",
    "STVAC2": "",
    "STVAC3": "STMB3",
    "STVAC4": "STMB4",
    "STVAC5": "STMB5",
    "STVAC6": "",
    "STVAC7": "",
    "STVAC8": "",
    "STVAC9": "",
    "STVAC10": "",
    "STVAC11": "STMB11",
    "STVAC12": "STMB12",
    "STVAC13": "STMB13",
    "STVAC14": "STMB14",
    "STVAC15": "STMB15",
    "STVAC16": "",
    "STVAC17": "",
    "STVAC18": "",
    "VALORISATION_DU_PARC_DE_VACCINATION": "",
    "VALVAC1": "",
    "VALVAC2": "",
    "VALVAC3": "",
    "VALVAC4": "",
    "VALVAC5": "",
    "VALVAC6": "",
    "SAUVAC1": "",
    "SAUVAC2": "",
    "SAUVAC3": "",
    "SAUVAC4": "",
    "SAUVAC5": "",
    "SAUVAC6": "",
    "SAUVAC6/1": "",
    "SAUVAC6/2": "",
    "SAUVAC6a": "",
    "SAUVAC7": "",
    "SAUVAC7/1": "",
    "SAUVAC7/2": "",
    "SAUVAC7/3": "",
    "SAUVAC8": "",
    "SAUVAC9": "",
    "SAUVAC10": "",
    "SAUVAC11": "",
    "SAUVAC12": "",
    "SAUVAC13": "",
    "SAUVAC14": "",
    "SAUVAC15": "",
    # fields in FICHE_MARCHES_A_BETAIL
    "FICHE_MARCHES_A_BETAIL": "",
    "IDENTIFICATION_DU_CO_EUR_ET_DE_L_ENQUETE": "IDENTIFICATION_DU_CO_TEUR_ET_DE_L_ENQUETE",
    "IDMB1": "IDUV1",
    "IDMB2": "IDUV2",
    "IDMB2a": "IDUV2A",
    "IDMB3": "IDUV3",
    "IDMB4": "",
    "IDMB5": "",
    "IDMB6": "",
    "IDMB7": "IDUV7",
    "IDMB8": "IDUV8",
    "IDMB9": "IDUV9",
    "LOCALISATION_DU_MARCHE_A_BETAIL": "LOCALISATION_DE_L_INFRASTRUCTURE",
    "LMB1": "LUV1",
    "LMB2": "LUV2",
    "LMB3": "LUV3",
    "LMB4": "LUV4",
    "LMB5": "LUV5",
    "LMB6": "LUV6",
    "_LMB6_latitude": "_LUV6_latitude",
    "_LMB6_longitude": "_LUV6_longitude",
    "_LMB6_altitude": "_LUV6_altitude",
    "_LMB6_precision": "_LUV6_precision",
    "LMB7": "LUV7",
    "LMB7a": "LUV7a",
    "LMB7a_URL": "LUV7a_URL",
    "LMB7b": "LUV7b",
    "LMB7b_URL": "LUV7b_URL",
    "LMB7c": "LUV7c",
    "LMB7c_URL": "LUV7c_URL",
    "LMB7d": "LUV7d",
    "LMB7d_URL": "LUV7d_URL",
    "LMB7e": "",
    "INFORMATION_GENERALE_LE_MARCHE_A_BETAIL": "",
    "IGMB1": "",
    "IGMB2": "",
    "IGMB3": "",
    "IGMB4": "",
    "IGMB5": "",
    "IGMB6": "",
    "IGMB7": "",
    "IGMB8": "",
    "IGMAA": "",
    "IGMAB": "",
    "IGMBA": "",
    "IGMBA1": "",
    "IGMBA2": "",
    "IGMBA3": "",
    "IGMBA4": "",
    "IGMBA5": "",
    "IGMBA6": "",
    "SUIVI_DES_TRAVAUX_DE_N_DU_MARCHE_A_BETAIL": "SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE",
    "STMB1": "STMB1",
    "STMB2": "",  # Unmatched label: Marches = caractéristiques, Simplifiée = entreprise
    "STMB3": "STMB3",
    "STMB4": "STMB4",
    "STMB5": "STMB5",
    "STMB6": "",
    "STMB7": "",
    "STMB8": "",
    "STMB9": "",
    "STMB10": "",
    "STMB11": "STMB11",
    "STMB12": "STMB12",
    "STMB13": "STMB13",
    "STMB14": "STMB14",
    "STMB15": "STMB15",
    "STMB16": "",  # Unmatched label: Marches = problemes mise en œuvre, Simplifiée = Tracker le couloir
    "STMB17": "",
    "STMB18": "",
    "QUELQUES_CRITERES_D_ONNALITE_DE_MARCHES": "",
    "CMOP1": "",
    "CMOP2": "",
    "CMOP3": "",
    "CMOP4": "",
    "CMOP5": "",
    "CMOP6": "",
    "VALORISATION_DU_MARCHE": "",
    "VALMB1": "",
    "VALMB2": "",
    "VALMB3": "",
    "VALMB4": "",
    "VALMB5": "",
    "VALMB6": "",
    "SAUMB1": "",
    "SAUMB2": "",
    "SAUMB3": "",
    "SAUMB4": "",
    "SAUMB5": "",
    "SAUMB6": "",
    "SAUMB6a": "",
    "SAUMB7": "",
    "SAUMB8": "",
    "SAUMB9": "",
    "SAUMB10": "",
    "SAUMB11": "",
    "SAUMB12": "",
    "SAUMB15": "",
    "SAUMB16": "",
    "SAUMB17": "",
    # fields in FICHE_UNITE_VETERINAIRE
    "FICHE_UNITE_VETERINAIRE": "",
    "IDUV1": "IDUV1",
    "IDUV2": "IDUV2",
    "IDUV2a": "IDUV2A",
    "IDUV3": "IDUV3",
    "IDUV4": "",
    "IDUV5": "",
    "IDUV6": "",
    "IDUV7": "IDUV7",
    "IDUV8": "IDUV8",
    "IDUV9": "IDUV9",
    "LOCALISATION_DE_L_UNITE_VETERINAIRE": "LOCALISATION_DE_L_INFRASTRUCTURE",
    "LUV1": "LUV1",
    "LUV2": "LUV2",
    "LUV3": "LUV3",
    "LUV4": "LUV4",
    "LUV5": "LUV5",
    "LUV6": "LUV6",
    "_LUV6_latitude": "_LUV6_latitude",
    "_LUV6_longitude": "_LUV6_longitude",
    "_LUV6_altitude": "_LUV6_altitude",
    "_LUV6_precision": "_LUV6_precision",
    "LUV7": "LUV7",
    "LUV7a": "LUV7a",
    "LUV7a_URL": "LUV7a_URL",
    "LUV7b": "LUV7b",
    "LUV7b_URL": "LUV7b_URL",
    "LUV7c": "LUV7c",
    "LUV7c_URL": "LUV7c_URL",
    "LUV7d": "LUV7d",
    "LUV7d_URL": "LUV7d_URL",
    "LUV7e": "",
    "INFORMATION_GENERALE_SUR_L_UNITE_VETERINAIRE": "",
    "IGUV1": "",
    "IGUV2": "",
    "IGUV3": "",
    "IGUV4": "",
    "IGUV5": "",
    "IGUV6": "",
    "IGUV7": "",
    "IGUV8": "",
    "IGUV9": "",
    "IGUV10": "",
    "IGUV11": "",
    "IGUV12": "",
    "SUIVI_DES_TRAVAUX_DE_L_UNITE_VETERINAIRE": "SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE",
    "STUV1": "STMB1",
    "STUV2": "",
    "STUV3": "STMB3",
    "STUV4": "STMB4",
    "STUV5": "STMB5",
    "STUV6": "",
    "STUV7": "",
    "STUV8": "",
    "STUV9": "",
    "STUV10": "",
    "STUV11": "STMB11",
    "STUV12": "STMB12",
    "STUV13": "STMB13",
    "STUV14": "STMB14",
    "STUV15": "STMB15",
    "STUV16": "",
    "STUV17": "",
    "STUV18": "",
    "QUELQUES_CRITERES_D_ONNALITE_DE_L_UNITE_VETERINAIRE": "",
    "CFUV1": "",
    "CFUV2": "",
    "CFUV3": "",
    "CFUV4": "",
    "CFUV5": "",
    "CFUV6": "",
    "VALORISATION_DE_L_UNITE_VETERINAIRE": "",
    "VALUV1": "",
    "VALUV2": "",
    "VALUV3": "",
    "VALUV4": "",
    "VALUV5": "",
    "VALUV6": "",
    "SAUUV1": "",
    "SAUUV2": "",
    "SAUUV3": "",
    "SAUUV4": "",
    "SAUUV5": "",
    "SAUUV6": "",
    "SAUUV6a": "",
    "SAUUV7": "",
    "SAUUV8": "",
    "SAUUV9": "",
    "SAUUV10": "",
    "SAUUV11": "",
    "SAUUV12": "",
    "SAUUV15": "",
    "SAUUV16": "",
    "SAUUV17": "",
    # fields in FICHE AIRE D'ABATTAGE, ETAL, MAGASINS, LATRINES_MALI
    "start": "starttime",
    "end": "endtime",
    "_1_Date_de_la_collecte": "DATE",
    "_2_Nom_et_pr_noms_du_collecteur": "IDUV1",
    "_3_Fonction_du_collecteur": "IDUV2",
    "_3a_Si_autre_pr_cisez": "IDUV2A",
    "_4_Contact_t_l_phonique_du_collecteur": "IDUV3",
    "_5_Nom_contr_leur": "",
    "_6_Fonction_du_contr_leur": "",
    "_7_Contact_t_l_phonique_du_contr_leur": "",
    "_2_Fonction_du_collecteur_001_002": "IDUV7",
    "_9_Fonction_de_l_enqu_t": "IDUV8",
    "_10_Contact_t_l_phonique_du_contr_leur": "IDUV9",
    "group_wx1xk15": "",
    "_11_Pays": "LUV1",
    "region": "LUV2",
    "cercle": "LUV3",
    "commune": "LUV4",
    "_15_Localit": "LUV5",
    "_16_Coordonn_es_g_og_de_l_aire_d_abattage": "LUV6",
    "__16_Coordonn_es_g_og_de_l_aire_d_abattage_latitude": "_LUV6_latitude",
    "__16_Coordonn_es_g_og_de_l_aire_d_abattage_longitude": "_LUV6_longitude",
    "__16_Coordonn_es_g_og_de_l_aire_d_abattage_altitude": "_LUV6_altitude",
    "__16_Coordonn_es_g_og_de_l_aire_d_abattage_precision": "_LUV6_precision",
    "group_yw28r74": "",
    "_17a_Prendre_la_phot_de_l_infrastructure": "LUV7a",
    "_17a_Prendre_la_phot_de_l_infrastructure_URL": "LUV7a_URL",
    "_17b_Prendre_la_phot_de_l_infrastructure": "LUV7b",
    "_17b_Prendre_la_phot_de_l_infrastructure_URL": "LUV7b_URL",
    "_17c_Prendre_la_phot_de_l_infrastructure": "LUV7c",
    "_17c_Prendre_la_phot_de_l_infrastructure_URL": "LUV7c_URL",
    "_17d_Prendre_la_phot_de_l_infrastructure": "LUV7d",
    "_17d_Prendre_la_phot_de_l_infrastructure_URL": "LUV7d_URL",
    "_18_Date_de_prise_des_photos": "",
    "group_dv4ft63": "",
    "_19_Types_d_infrastructures": "",
    "_19_Quelles_sont_les_sources_d": "",
    "_20_Quel_est_le_statut_de_l_infrastructure": "",
    "_21_Si_co_financemen_rtenaires_financiers": "",
    "_22_Quel_est_le_co_t_de_r_alisation_FCFA": "",
    "_23_en_cas_de_co_fin_r_le_PRAPS_2_en_FCFA": "",
    "_23_L_aire_d_abattage_dispose_": "",
    "_25_Si_non_pourquoi": "",
    "_26_quel_est_l_effec_des_membre_du_comit": "",
    "_27_Combien_de_femme_mbres_comporte_t_il_": "",
    "_28A_De_combien_de_m_le_bureau_du_comit_": "",
    "_28B_Quel_est_l_effe_du_bureau_du_comit_": "",
    "_27C_Quels_sont_les_postes_occ": "",
    "_28D_Si_autre_pr_cisez": "",
    "_28E_Le_comit_est_i_nt_pour_v_rification": "",
    "_28F_Les_membres_du_voir_PV_de_r_union": "",
    "_28G_Quelles_sont_vo_ctionnement_du_comit": "",
    "_28H_De_quels_renfor_s_et_responsabilit_s": "",
    "_28I_Quelles_sont_vo_du_comit_de_gestion": "",
    "group_zj9me34": "",
    "_29_Quelle_est_la_na_des_travaux_r_alis_s": "STMB1",
    "_30_D_crire_quelques_fications_techniques": "",
    "_31_Quelle_est_la_da_ncement_des_travaux_": "STMB3",
    "_32_Quelle_est_la_du_s_travaux_en_mois_": "STMB4",
    "_33_Pr_cisez_le_niveau_de_mise": "STMB5",
    "_34_Si_pas_encore_d_marr_pourquoi": "",
    "_35_Si_retard_pourquoi": "",
    "_36_Quelles_sont_les_les_travaux_temps": "",
    "_37_Si_arr_t_pourquoi": "",
    "_38_Quelles_sont_les_r_lancer_les_travaux": "",
    "_39_Si_r_ception_pro_er_la_date_voir_PV": "STMB11",
    "_40_Si_r_ception_pro_er_la_date_voir_PV": "STMB12",
    "_41_Si_r_ception_d_f_er_la_date_voir_PV": "STMB13",
    "_42_Pr_cisez_le_taux_la_date_de_l_enqu_te": "STMB15",
    "_43_Le_site_est_il_confront_a": "",
    "_44_Si_oui_lesquels": "",
    "_45_Quelles_sont_les_re_pour_les_resoudre": "",
    "group_eq6iz00": "",
    "_46_Selon_vous_le_comit_de_g": "",
    "_47_Si_non_pourquoi": "",
    "_48_La_mise_en_place_services_de_l_levage": "",
    "_49_L_accord_convent_isation_r_partition": "",
    "_50_Si_non_pourquoi": "",
    "_51_Le_d_marrage_des_sur_l_infrastructure": "",
    "group_en1yb15": "",
    "_52_Selon_vous_l_aire_d_abatt": "",
    "_53_Si_non_pourquoi": "",
    "_54_A_combien_peut_o_de_l_infrastructure": "",
    "_55_Le_site_est_il_confront_a": "",
    "_56_Si_oui_lesquels": "",
    "_57_Quelles_sont_les_re_pour_les_resoudre": "",
    "group_ar25y78": "",
    "_58_Tous_les_travail_es_sur_le_Genre_VBG": "",
    "_59_Le_chantier_disp_tion_collective_EPC": "",
    "_60_Les_travailleurs_on_individuelle_EPI": "",
    "_61_Le_site_est_il_couvert_par": "",
    "_62_Si_non_pourquoi": "",
    "_63_A_quel_niveau_les_plainte": "",
    "_63a_Si_autre_pr_cisez": "",
    "_64_Quels_sont_les_types_de_pl": "",
    "_65_Si_plaintes_sens_laintes_enregistr_es": "",
    "_66_Si_plaintes_sens_t_protocoles_tablis": "",
    "_67_Quel_est_le_nomb_Bas_es_sur_le_Genre": "",
    "_68_Si_plaintes_non_laintes_enregistr_es": "",
    "_69_Si_plaintes_non_t_protocoles_tablis": "",
    "_70_Quels_autres_eff_ulation_b_n_ficiaire": "",
    "_71_Quels_autres_eff_ulation_b_n_ficiaire": "",
    "_72_Quels_sont_vos_o_commentaires_de_fin": "CONFSITE2",
}

name_label_mapping = {
    "IDENTIFICATION_DU_CO_TEUR_ET_DE_L_ENQUETE": "IDENTIFICATION DU COLLECTEUR ET DE L’ENQUETE",
    "DATE": "1) Date de la collecte",
    "IDUV1": "2) Nom et prénoms du collecteur",
    "IDUV2": "3) Fonction du collecteur",
    "IDUV2A": "3a)  Si autre, précisez",
    "IDUV3": "4) Contact téléphonique du collecteur",
    "IDUV7": "5) Nom de l’enquêté",
    "IDUV8": "6) Fonction de l’enquêté",
    "IDUV9": "7) Contact téléphonique de l’enquêté",
    "group2": "Informations sur l’infrastructure",
    "TYPE": "8) Nature de l'indicateur",
    "CDR": "9) Type d'infrastructure CRD réalisé",
    "IGPE0": "10) Choisir le type d'unité vétérinaire concerné",
    "IGPE0a": "10a) Si autre (Précisez )",
    "IGPE1": "11) Choisir le type de point d’eau pastoral concerné",
    "IGPE1a": "11a) Si autre (Précisez )",
    "IGPE2": "12) Quels sont les moyens d’exhaure du point d'eau?",
    "IGPE2a": "12a) Si autre (Précisez )",
    "HCDR": "13) Type d'infrastructure Hors CRD réalisé",
    "STMB2": "14) Quel est le nom de l'entreprise en charge des travaux?",
    "STMB0": "15) Est-ce la première collecte de données sur ce site ?",
    "IDT": "16) Saisie de l’identifiant de l’infrastructure",
    "STMB01": "17) Nom de l'organisme en charge du contrôle des travaux",
    "STMB02": "18) Nom et prénom du représentant légal ou du responsable du bureau de contrôle",
    "STMB03": "19) Contact du représentant légal du bureau de contrôle",
    "group2-1": "Localisation de l’infrastructure",
    "LUV1": "20) Pays",
    "LUV2": "21) Region/Wilaya/Province",
    "LUV3": "22) Province/Cercle/Moughataa/Departement",
    "LUV4": "23) Commune/Sous-Préfecture",
    "LUV5": "24) Localité",
    "LUV6_existing": "25) Veuillez sélectionner sur la carte le point existant",
    "LUV6_manual": "25) Veuillez entrer les coordonnées géographiques de l'infrastructure",
    "IDT2": "Identifiant de l’infrastructure: ${INFRASTRUCTURE_ID}",
    "SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE": "SUIVI DES TRAVAUX DE REALISATION D'INFRASTRUCTURE",
    "STMB1": "26) Quelle est la nature des travaux  réalisés?",
    "STMB3": "27) Quelle est la date effective de lancement des travaux ?",
    "STMB4": "28) Quelle est la durée prévisionnelle de réalisation des travaux (en mois)?",
    "STMB5": "29) Précisez  le niveau de mise en œuvre des travaux  sur le site",
    "STMB11": "30) Si réception provisoire avec réserve,  préciser la date  (voir Procès-verbal /PV)",
    "STMB12": "31) Si réception provisoire  sans reserve, préciser la date  (voir Procès-verbal /PV)",
    "STMB13": "32) Si réception définitive, préciser la date  (voir Procès- verbal /PV)",
    "STMB15": "33) Précisez le taux de réalisation des travaux à la date de l’enquête",
    "CONFSITE": "Observations sur le site",
    "CONFSITE1": "34) Quelle est la qualité globale des travaux réalisés?",
    "DATTROL": "35) Quelle est la date de la dernière visite du Bureau de contrôle ?",
    "CONFSITE2": "36) Quels sont vos commentaires généraux sur l'exécution des travaux sur le chantier?",
    "group3-1": "Tracking de couloir",
    "STMB16": "37) Tracker le couloir",
    "note4": "38) La distance trackée est ${STMB18} Kilomètre (s)",
    "LUV7": "Prendre quelques photos de l’infrastructure sous plusieurs angles ou facettes",
    "LUV7a": "39a) Prendre la photo de l’infrastructure",
    "LUV7b": "39b) Prendre la photo de l’infrastructure",
    "LUV7c": "39c) Prendre la photo de l’infrastructure",
    "LUV7d": "39d) Prendre la photo de l’infrastructure",
}

duplicates_manual_correction_mapping = {  # based on feedbacks from countries (see --> https://docs.google.com/spreadsheets/d/1C_fjS4LL-H2NP55VCRVyMFl9EfCeLFsG/edit?gid=343881162#gid=343881162)
    "f3adb1e2-62e6-4777-be00-d828aa523d70": "131da68d-55e6-49b5-aea8-53c2f7ddbc60",
    "40ed8b89-5bcc-48da-9ccf-48b4d825a908": "474c8b3b-1d79-4881-ac9e-8eacd96c1d88",
    "d562c864-7de6-4de1-8891-c7739c1bbc09": "f9d31dde-34b7-4525-92e7-ae7dcf4db520",
    "d8cfaded-c6ce-459a-8d53-b47fe596d63b": "d49448c7-7533-4774-ba43-1e3c79e4cd2c",
    "b95dc24e-592f-4f7f-b8d2-8b2948e4c09d": "eb9e7efa-760b-4812-81ee-422ad16663b1",
    "db0d86b2-c6a9-4e81-b11c-1501b54a79d0": "2cc112e5-7cbf-4e1f-935e-e5d0227f6490",
    "dcc5a0fe-0f1f-4d92-893d-432c7d849469": "6787896f-f8c7-46c2-9094-3de087124ffe",
    "44647f52-0e3a-43ab-ba33-f2823fe2368d": "5f86bb35-bcd8-486d-9bf1-76670e9662ba",
}

entry_errors = [
    "76bfed1d-fbf9-415c-9a68-a9cda24ad231"
]  # based on feedbacks from countries (see --> https://docs.google.com/spreadsheets/d/1C_fjS4LL-H2NP55VCRVyMFl9EfCeLFsG/edit?gid=343881162#gid=343881162)
