"""Legacy column schemas for the extract-surveys pipeline.

Reconstructs the column shape of each of the 4 output tables as it existed BEFORE the
11-survey -> 1-consolidated-survey migration, plus the consolidated -> legacy field
renames needed to populate them. This is the source of truth for the Geonode layer
configuration -- DO NOT rename or remove entries in LEGACY_COLUMNS.

LEGACY_COLUMNS: derived 2026-08-04 from the reference parquet files shipped beside this
pipeline (schema + column order only, read via `pl.scan_parquet(...).collect_schema()`):
    extract_surveys/marches_a_betail.parquet
    extract_surveys/parcs_de_vaccination.parquet
    extract_surveys/points_d_eau.parquet
    extract_surveys/unites_veterinaires.parquet

COLUMN_RENAMES: derived 2026-08-04 from `all_forms_cols_mapping` in
    add_infrastructure_id/config.py
That dict maps legacy-survey field name -> consolidated field name; the entries below
are the inverse (consolidated -> legacy), partitioned by originating survey, with
identity mappings and empty (no-consolidated-equivalent) targets dropped.

One deliberate deviation from the raw reference parquet (2026-08-04, per Lionel): every
"infrastructure_id" entry below is typed pl.String, not the pl.UInt32 found in the
reference parquet. That UInt32 column was a dead row-index leftover from the
now-permanently-disabled `identify_duplicates()`/`with_row_index()` code and never held
real data. The consolidated survey's real, populated identifier ("INFRASTRUCTURE_ID",
uppercase) is folded into this same lowercase column by `transform_survey` -- keeping
both around as separate columns made every gpkg/PostGIS write raise `FieldError: Error
adding field 'INFRASTRUCTURE_ID' to layer`, since GDAL's GPKG driver rejects field names
that differ only by case.
"""

from typing import Dict

import polars as pl

LEGACY_COLUMNS: Dict[str, Dict[str, pl.DataType]] = {
    "marches_a_betail": {
        "infrastructure_id": pl.String,  # deliberate deviation from raw parquet (was UInt32); see surveys.py transform_survey
        "_id": pl.Int64,
        "starttime": pl.String,
        "endtime": pl.String,
        "deviceid": pl.String,
        "devicephonenum": pl.String,
        "DATE": pl.Date,
        "IDMB1": pl.String,
        "IDMB2": pl.String,
        "IDMB3": pl.String,
        "IDMB4": pl.String,
        "IDMB5": pl.String,
        "IDMB6": pl.String,
        "IDMB7": pl.String,
        "IDMB8": pl.String,
        "IDMB9": pl.String,
        "LMB1": pl.String,
        "LMB2": pl.String,
        "LMB3": pl.String,
        "LMB4": pl.String,
        "LMB5": pl.String,
        "LMB6": pl.String,
        "LMB7a": pl.String,
        "LMB7b": pl.String,
        "LMB7c": pl.String,
        "LMB7e": pl.Date,
        "IGMB1": pl.String,
        "IGMB3": pl.String,
        "IGMB5": pl.String,
        "IGMB7": pl.Int64,
        "IGMB8": pl.Int64,
        "IGMAA": pl.Int64,
        "IGMAB": pl.Int64,
        "IGMBA": pl.String,
        "IGMBA2": pl.String,
        "IGMBA3": pl.String,
        "IGMBA4": pl.String,
        "IGMBA5": pl.String,
        "IGMBA6": pl.String,
        "STMB1": pl.String,
        "STMB2": pl.String,
        "STMB3": pl.Date,
        "STMB4": pl.Int64,
        "STMB5": pl.String,
        "STMB14": pl.String,
        "STMB15": pl.String,
        "CMOP1": pl.String,
        "CMOP3": pl.String,
        "CMOP4": pl.String,
        "CMOP6": pl.String,
        "SAUMB1": pl.String,
        "SAUMB2": pl.String,
        "SAUMB3": pl.String,
        "SAUMB4": pl.String,
        "SAUMB5": pl.String,
        "SAUMB6": pl.String,
        "SAUMB7": pl.String,
        "SAUMB15": pl.String,
        "SAUMB16": pl.String,
        "SAUMB17": pl.String,
        "instanceID": pl.String,
        "rootUuid": pl.String,
        "instanceName": pl.String,
        "deprecatedID": pl.String,
        "uuid": pl.String,
        "__version__": pl.String,
        "_xform_id_string": pl.String,
        "_uuid": pl.String,
        "_attachments": pl.String,
        "_status": pl.String,
        "_geolocation": pl.String,
        "_submission_time": pl.String,
        "_validation_status": pl.String,
        "_submitted_by": pl.String,
        "LMB7d": pl.String,
        "STMB12": pl.Date,
        "VALMB1": pl.String,
        "VALMB3": pl.Int64,
        "VALMB4": pl.String,
        "IGMBA1": pl.String,
        "STMB6": pl.String,
        "STMB16": pl.String,
        "SAUMB6a": pl.String,
        "IGMB6": pl.String,
        "CMOP2": pl.String,
        "CMOP5": pl.String,
        "SAUMB8": pl.Int64,
        "SAUMB9": pl.Int64,
        "SAUMB10": pl.Int64,
        "SAUMB11": pl.Int64,
        "SAUMB12": pl.Int64,
        "STMB11": pl.Date,
        "IDMB2a": pl.String,
        "STMB7": pl.String,
        "STMB8": pl.String,
        "STMB9": pl.String,
        "STMB10": pl.String,
        "STMB13": pl.Date,
        "VALMB2": pl.String,
        "VALMB5": pl.String,
        "VALMB6": pl.String,
        "IGMB2": pl.String,
        "IGMB4": pl.String,
        "STMB17": pl.String,
        "STMB18": pl.String,
        "validation_status": pl.String,
        "LATITUDE": pl.Float64,
        "LONGITUDE": pl.Float64,
        "level_2": pl.String,
        "level_3": pl.String,
        "level_4": pl.String,
        "level_5": pl.String,
        "level_6": pl.String,
        "level_7": pl.String,
        "STATE": pl.String,
        "PROGRESS": pl.String,
        "column_localite": pl.String,
    },
    "parcs_de_vaccination": {
        "infrastructure_id": pl.String,  # deliberate deviation from raw parquet (was UInt32); see surveys.py transform_survey
        "_id": pl.Int64,
        "uuid": pl.String,
        "starttime": pl.String,
        "endtime": pl.String,
        "deviceid": pl.String,
        "DATE": pl.Date,
        "IDVAC1": pl.String,
        "IDVAC2": pl.String,
        "IDVAC2a": pl.String,
        "IDVAC3": pl.String,
        "IDVAC4": pl.String,
        "IDVAC5": pl.String,
        "IDVAC6": pl.String,
        "IDVAC7": pl.String,
        "IDVAC8": pl.String,
        "IDVAC9": pl.String,
        "LVAC1": pl.String,
        "LVAC2": pl.String,
        "LVAC3": pl.String,
        "LVAC4": pl.String,
        "LVAC5": pl.String,
        "LVAC6": pl.String,
        "LVAC8a": pl.String,
        "LVAC8b": pl.String,
        "LVAC8c": pl.String,
        "LVAC8d": pl.String,
        "LVAC9": pl.Date,
        "IGVAC1": pl.String,
        "IGVAC2": pl.String,
        "IGVAC3": pl.String,
        "IGVAC4": pl.String,
        "IGVAC5": pl.String,
        "IGVAC7": pl.String,
        "IGVAC9": pl.String,
        "IGVAC10": pl.String,
        "STVAC1": pl.String,
        "STVAC2": pl.String,
        "STVAC3": pl.Date,
        "STVAC4": pl.Int64,
        "STVAC5": pl.String,
        "STVAC14": pl.String,
        "STVAC15": pl.String,
        "SAUVAC1": pl.String,
        "SAUVAC2": pl.String,
        "SAUVAC3": pl.String,
        "SAUVAC4": pl.String,
        "SAUVAC6": pl.String,
        "SAUVAC6a": pl.String,
        "SAUVAC7": pl.String,
        "SAUVAC15": pl.String,
        "__version__": pl.String,
        "instanceID": pl.String,
        "instanceName": pl.String,
        "_xform_id_string": pl.String,
        "_uuid": pl.String,
        "_attachments": pl.String,
        "_status": pl.String,
        "_geolocation": pl.String,
        "_submission_time": pl.String,
        "_validation_status": pl.String,
        "_submitted_by": pl.String,
        "rootUuid": pl.String,
        "devicephonenum": pl.String,
        "IGVAC11": pl.Int64,
        "IGVAC12": pl.Int64,
        "IGVAC12I": pl.Int64,
        "IGVAC12C": pl.Int64,
        "IGVAC12A": pl.String,
        "IGVAC12A1": pl.String,
        "IGVAC12A2": pl.String,
        "IGVAC12A3": pl.String,
        "IGVAC12A4": pl.String,
        "IGVAC12A5": pl.String,
        "IGVAC12A6": pl.String,
        "STVAC6": pl.String,
        "STVAC16": pl.String,
        "deprecatedID": pl.String,
        "SAUVAC5": pl.String,
        "STVAC12": pl.Date,
        "VALVAC1": pl.String,
        "VALVAC3": pl.Int64,
        "VALVAC4": pl.String,
        "SAUVAC11": pl.Int64,
        "SAUVAC12": pl.Int64,
        "SAUVAC13": pl.String,
        "SAUVAC14": pl.String,
        "STVAC11": pl.Date,
        "STVAC7": pl.String,
        "STVAC8": pl.String,
        "STVAC9": pl.String,
        "STVAC10": pl.String,
        "STVAC13": pl.Date,
        "SAUVAC8": pl.Int64,
        "SAUVAC9": pl.Int64,
        "SAUVAC10": pl.Int64,
        "IGVAC6": pl.String,
        "IGVAC8": pl.String,
        "STVAC17": pl.String,
        "STVAC18": pl.String,
        "VALVAC2": pl.String,
        "VALVAC5": pl.String,
        "VALVAC6": pl.String,
        "validation_status": pl.String,
        "LATITUDE": pl.Float64,
        "LONGITUDE": pl.Float64,
        "level_2": pl.String,
        "level_3": pl.String,
        "level_4": pl.String,
        "level_5": pl.String,
        "level_6": pl.String,
        "level_7": pl.String,
        "STATE": pl.String,
        "PROGRESS": pl.String,
        "column_localite": pl.String,
    },
    "points_d_eau": {
        "infrastructure_id": pl.String,  # deliberate deviation from raw parquet (was UInt32); see surveys.py transform_survey
        "_id": pl.Int64,
        "starttime": pl.String,
        "endtime": pl.String,
        "deviceid": pl.String,
        "devicephonenum": pl.String,
        "DATE": pl.Date,
        "IDPE1": pl.String,
        "IDPE2": pl.String,
        "IDPE3": pl.String,
        "IDPE4": pl.String,
        "IDPE5": pl.String,
        "IDPE6": pl.String,
        "IDPE7": pl.String,
        "IDPE8": pl.String,
        "IDPE9": pl.String,
        "LPE1": pl.String,
        "LPE2": pl.String,
        "LPE3": pl.String,
        "LPE4": pl.String,
        "LPE5": pl.String,
        "LPE6": pl.String,
        "LPE7": pl.String,
        "LPE8a": pl.String,
        "LPE8b": pl.String,
        "LPE8c": pl.String,
        "LPE9": pl.Date,
        "IGPE1": pl.String,
        "IGPE2": pl.String,
        "IGPE4": pl.String,
        "IGPE6": pl.String,
        "IGPE7": pl.String,
        "STPE1": pl.String,
        "STPE2": pl.String,
        "STPE3": pl.Date,
        "STPE4": pl.Int64,
        "STPE5": pl.String,
        "STPE6": pl.String,
        "STPE14": pl.String,
        "STPE16": pl.String,
        "CFPE1": pl.String,
        "CFPE2": pl.String,
        "CFPE4": pl.String,
        "CFPE6": pl.String,
        "SAUPE1": pl.String,
        "SAUPE2": pl.String,
        "SAUPE3": pl.String,
        "SAUPE4": pl.String,
        "SAUPE5": pl.String,
        "SAUPE6": pl.String,
        "SAUPE7": pl.String,
        "SAUPE13": pl.String,
        "SAUPE14": pl.String,
        "SAUPE15": pl.String,
        "instanceID": pl.String,
        "rootUuid": pl.String,
        "instanceName": pl.String,
        "deprecatedID": pl.String,
        "uuid": pl.String,
        "__version__": pl.String,
        "_xform_id_string": pl.String,
        "_uuid": pl.String,
        "_attachments": pl.String,
        "_status": pl.String,
        "_geolocation": pl.String,
        "_submission_time": pl.String,
        "_validation_status": pl.String,
        "_submitted_by": pl.String,
        "IDPE2a": pl.String,
        "IGPE10": pl.Int64,
        "IGPE11": pl.Int64,
        "IGPE11A1": pl.Int64,
        "IGPE11A2": pl.Int64,
        "IGPE11A3": pl.String,
        "IGPE11A5": pl.String,
        "IGPE11A6": pl.String,
        "IGPE11A7": pl.String,
        "IGPE11A8": pl.String,
        "IGPE11A9": pl.String,
        "STPE12": pl.Date,
        "STPE15": pl.String,
        "VALPE1": pl.String,
        "VALPE3": pl.Int64,
        "VALPE4": pl.String,
        "SAUPE6a": pl.String,
        "SAUPE8": pl.Int64,
        "SAUPE9": pl.Int64,
        "SAUPE10": pl.Int64,
        "LPE8d": pl.String,
        "IGPE11A4": pl.String,
        "CFPE1a": pl.String,
        "CFPE3": pl.String,
        "CFPE5": pl.String,
        "SAUPE11": pl.Int64,
        "SAUPE12": pl.Int64,
        "STPE7": pl.String,
        "STPE8": pl.String,
        "STPE13": pl.Date,
        "STPE11": pl.Date,
        "CFPE7": pl.String,
        "IGPE1a": pl.String,
        "IDPE8a": pl.String,
        "IGPE3": pl.String,
        "IGPE5": pl.String,
        "STPE9": pl.String,
        "STPE10": pl.String,
        "STPE17": pl.String,
        "STPE18": pl.String,
        "VALPE2": pl.String,
        "VALPE5": pl.String,
        "VALPE6": pl.String,
        "validation_status": pl.String,
        "LATITUDE": pl.Float64,
        "LONGITUDE": pl.Float64,
        "level_2": pl.String,
        "level_3": pl.String,
        "level_4": pl.String,
        "level_5": pl.String,
        "level_6": pl.String,
        "level_7": pl.String,
        "STATE": pl.String,
        "PROGRESS": pl.String,
        "column_localite": pl.String,
    },
    "unites_veterinaires": {
        "infrastructure_id": pl.String,  # deliberate deviation from raw parquet (was UInt32); see surveys.py transform_survey
        "_id": pl.Int64,
        "uuid": pl.String,
        "starttime": pl.String,
        "endtime": pl.String,
        "deviceid": pl.String,
        "DATE": pl.Date,
        "IDUV1": pl.String,
        "IDUV2": pl.String,
        "IDUV3": pl.String,
        "IDUV4": pl.String,
        "IDUV5": pl.String,
        "IDUV6": pl.String,
        "IDUV7": pl.String,
        "IDUV8": pl.String,
        "IDUV9": pl.String,
        "LUV1": pl.String,
        "LUV2": pl.String,
        "LUV3": pl.String,
        "LUV4": pl.String,
        "LUV5": pl.String,
        "LUV6": pl.String,
        "LUV7a": pl.String,
        "LUV7b": pl.String,
        "LUV7c": pl.String,
        "LUV7d": pl.String,
        "LUV8": pl.Date,
        "IGUV1": pl.String,
        "IGUV3": pl.String,
        "STUV1": pl.String,
        "STUV2": pl.String,
        "STUV3": pl.Date,
        "STUV4": pl.Int64,
        "STUV5": pl.String,
        "STUV6": pl.String,
        "STUV14": pl.String,
        "STUV16": pl.String,
        "CFUV1": pl.String,
        "CFUV2": pl.String,
        "CFUV3": pl.String,
        "CFUV4": pl.String,
        "SAUUV1": pl.String,
        "SAUUV2": pl.String,
        "SAUUV3": pl.String,
        "SAUUV4": pl.String,
        "SAUUV5": pl.String,
        "SAUUV6": pl.String,
        "SAUUV7": pl.String,
        "SAUUV13": pl.String,
        "SAUUV14": pl.String,
        "SAUUV15": pl.String,
        "__version__": pl.String,
        "instanceID": pl.String,
        "instanceName": pl.String,
        "_xform_id_string": pl.String,
        "_uuid": pl.String,
        "rootUuid": pl.String,
        "_attachments": pl.String,
        "_status": pl.String,
        "_geolocation": pl.String,
        "_submission_time": pl.String,
        "_validation_status": pl.String,
        "_submitted_by": pl.String,
        "devicephonenum": pl.String,
        "SAUUV6a": pl.String,
        "deprecatedID": pl.String,
        "STUV12": pl.Date,
        "STUV15": pl.String,
        "VALPE1": pl.String,
        "VALPE3": pl.Int64,
        "VALPE4": pl.String,
        "STUV11": pl.Date,
        "STUV7": pl.String,
        "STUV8": pl.String,
        "CFUV5": pl.String,
        "SAUUV8": pl.Int64,
        "SAUUV9": pl.Int64,
        "SAUUV10": pl.Int64,
        "IDUV2A": pl.String,
        "STUV13": pl.Date,
        "SAUUV11": pl.Int64,
        "SAUUV12": pl.Int64,
        "STUV9": pl.String,
        "STUV10": pl.String,
        "VALPE2": pl.String,
        "VALPE5": pl.String,
        "VALPE6": pl.String,
        "IGUV2": pl.String,
        "IGUV4": pl.String,
        "STUV17": pl.String,
        "STUV18": pl.String,
        "validation_status": pl.String,
        "LATITUDE": pl.Float64,
        "LONGITUDE": pl.Float64,
        "level_2": pl.String,
        "level_3": pl.String,
        "level_4": pl.String,
        "level_5": pl.String,
        "level_6": pl.String,
        "level_7": pl.String,
        "STATE": pl.String,
        "PROGRESS": pl.String,
        "column_localite": pl.String,
    },
}

COLUMN_RENAMES: Dict[str, Dict[str, str]] = {
    "marches_a_betail": {
        'IDENTIFICATION_DU_CO_TEUR_ET_DE_L_ENQUETE': 'IDENTIFICATION_DU_CO_EUR_ET_DE_L_ENQUETE',
        'IDUV1': 'IDMB1',
        'IDUV2': 'IDMB2',
        'IDUV2A': 'IDMB2a',
        'IDUV3': 'IDMB3',
        'IDUV7': 'IDMB7',
        'IDUV8': 'IDMB8',
        'IDUV9': 'IDMB9',
        'LOCALISATION_DE_L_INFRASTRUCTURE': 'LOCALISATION_DU_MARCHE_A_BETAIL',
        'LUV1': 'LMB1',
        'LUV2': 'LMB2',
        'LUV3': 'LMB3',
        'LUV4': 'LMB4',
        'LUV5': 'LMB5',
        'LUV6': 'LMB6',
        '_LUV6_latitude': '_LMB6_latitude',
        '_LUV6_longitude': '_LMB6_longitude',
        '_LUV6_altitude': '_LMB6_altitude',
        '_LUV6_precision': '_LMB6_precision',
        'LUV7': 'LMB7',
        'LUV7a': 'LMB7a',
        'LUV7a_URL': 'LMB7a_URL',
        'LUV7b': 'LMB7b',
        'LUV7b_URL': 'LMB7b_URL',
        'LUV7c': 'LMB7c',
        'LUV7c_URL': 'LMB7c_URL',
        'LUV7d': 'LMB7d',
        'LUV7d_URL': 'LMB7d_URL',
        'SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE': 'SUIVI_DES_TRAVAUX_DE_N_DU_MARCHE_A_BETAIL',
    },
    "parcs_de_vaccination": {
        'IDUV1': 'IDVAC1',
        'IDUV2': 'IDVAC2',
        'IDUV2A': 'IDVAC2a',
        'IDUV3': 'IDVAC3',
        'IDUV7': 'IDVAC7',
        'IDUV8': 'IDVAC8',
        'IDUV9': 'IDVAC9',
        'LOCALISATION_DE_L_INFRASTRUCTURE': 'LOCALISATION_DU_PARC_DE_VACCINATION',
        'LUV1': 'LVAC1',
        'LUV2': 'LVAC2',
        'LUV3': 'LVAC3',
        'LUV4': 'LVAC4',
        'LUV5': 'LVAC5',
        'LUV6': 'LVAC6',
        '_LUV6_latitude': '_LVAC6_latitude',
        '_LUV6_longitude': '_LVAC6_longitude',
        '_LUV6_altitude': '_LVAC6_altitude',
        '_LUV6_precision': '_LVAC6_precision',
        'LUV7': 'Prendre_quelques_ph_s_angles_ou_facettes',
        'LUV7a': 'LVAC8a',
        'LUV7a_URL': 'LVAC8a_URL',
        'LUV7b': 'LVAC8b',
        'LUV7b_URL': 'LVAC8b_URL',
        'LUV7c': 'LVAC8c',
        'LUV7c_URL': 'LVAC8c_URL',
        'LUV7d': 'LVAC8d',
        'LUV7d_URL': 'LVAC8d_URL',
        'SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE': 'SUIVI_DES_TRAVAUX_DE_U_PARC_A_VACCINATION',
        'STMB1': 'STVAC1',
        'STMB3': 'STVAC3',
        'STMB4': 'STVAC4',
        'STMB5': 'STVAC5',
        'STMB11': 'STVAC11',
        'STMB12': 'STVAC12',
        'STMB13': 'STVAC13',
        'STMB14': 'STVAC14',
        'STMB15': 'STVAC15',
    },
    "points_d_eau": {
        'IDUV1': 'IDPE1',
        'IDUV2': 'IDPE2',
        'IDUV2A': 'IDPE2a',
        'IDUV3': 'IDPE3',
        'IDUV7': 'IDPE7',
        'IDUV8': 'IDPE8',
        'IDUV9': 'IDPE9',
        'LOCALISATION_DE_L_INFRASTRUCTURE': 'LOCALISATION_DU_POINT_D_EAU_PASTORAL',
        'LUV1': 'LPE1',
        'LUV2': 'LPE2',
        'LUV3': 'LPE3',
        'LUV4': 'LPE4',
        'LUV5': 'LPE5',
        'LUV6': 'LPE7',
        '_LUV6_latitude': '_LPE7_latitude',
        '_LUV6_longitude': '_LPE7_longitude',
        '_LUV6_altitude': '_LPE7_altitude',
        '_LUV6_precision': '_LPE7_precision',
        'LUV7': 'LPE8',
        'LUV7a': 'LPE8a',
        'LUV7a_URL': 'LPE8a_URL',
        'LUV7b': 'LPE8b',
        'LUV7b_URL': 'LPE8b_URL',
        'LUV7c': 'LPE8c',
        'LUV7c_URL': 'LPE8c_URL',
        'LUV7d': 'LPE8d',
        'LUV7d_URL': 'LPE8d_URL',
        'SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE': 'SUIVI_DES_TRAVAUX_DE_POINT_D_EAU_PASTORAL',
        'STMB1': 'STPE1',
        'STMB3': 'STPE3',
        'STMB4': 'STPE4',
        'STMB5': 'STPE5',
        'STMB11': 'STPE11',
        'STMB12': 'STPE12',
        'STMB13': 'STPE13',
        'STMB14': 'STPE14',
        'STMB15': 'STPE15',
        'IGPE2': 'CFPE1',
        'IGPE2a': 'CFPE1a',
    },
    "unites_veterinaires": {
        # NOT 'IDUV2A': 'IDUV2a' -- all_forms_cols_mapping spells the old unites_veterinaires
        # field "IDUV2a" (lowercase a), but the real reference parquet's column is "IDUV2A"
        # (uppercase), identical to the consolidated name. Source A (the parquet) wins per
        # CLAUDE.md §5.1; that rename entry is a stale/typo'd mapping and applying it both
        # loses the real data under a wrongly-cased column and recreates the exact
        # GDAL case-collision this file exists to avoid.
        'LOCALISATION_DE_L_INFRASTRUCTURE': 'LOCALISATION_DE_L_UNITE_VETERINAIRE',
        'SUIVI_DES_TRAVAUX_DE_ION_D_INFRASTRUCTURE': 'SUIVI_DES_TRAVAUX_DE_L_UNITE_VETERINAIRE',
        'STMB1': 'STUV1',
        'STMB3': 'STUV3',
        'STMB4': 'STUV4',
        'STMB5': 'STUV5',
        'STMB11': 'STUV11',
        'STMB12': 'STUV12',
        'STMB13': 'STUV13',
        'STMB14': 'STUV14',
        'STMB15': 'STUV15',
    },
    # infrastructures_hors_cdr: all_forms_cols_mapping DOES define an entry here (the
    # Mali-only "FICHE AIRE D'ABATTAGE..." pilot block, e.g.
    # 'DATE': '_1_Date_de_la_collecte', 'IDUV1': '_2_Nom_et_pr_noms_du_collecteur', ...),
    # and it was applied in an earlier pass. Reverted (2026-08-04): renaming 'DATE' away
    # broke `concatenate_snapshots`, which hard-codes column_date="DATE" for every output
    # table -- confirmed via `polars.exceptions.ColumnNotFoundError: "DATE" not found`.
    # Unlike the other 4 tables, infrastructures_hors_cdr has no downstream consumer that
    # needs those Mali-specific xpath-derived names (that one-off pilot form's export was
    # never a Geonode-facing table), so there is no compatibility benefit to weigh against
    # that risk. Left empty on purpose: this table keeps plain consolidated field names.
    "infrastructures_hors_cdr": {},
}
